### ISSUE TITLE
Unable to see vendor's list after selecting delivery address during checkout

### ISSUE THREAD

**Issue by BunmiAdelana** [BunmiAdelana/Marketplace#1]
https://github.com/BunmiAdelana/Marketplace/assets/145928938/47a1ee41-b29a-4bb8-866f-f797d62265cd

**Comment by rebekah-oj** [comment]
vendor list is the list of all vendors on the marketplace, vendor list should not be showing on checkout @BunmiAdelana

**Comment by BunmiAdelana** [comment]
@rebekah-oj that was what I saw on the requirement document. I'll tag you to it on the PRD document

**Comment by BunmiAdelana** [comment]
@rebekah-oj ill be closing this now as the requirement isn't necessary
