### ISSUE TITLE
User should be able to see product name, image(s), product description, add on options with names, images, price, average rating, and tag. However I wasn't able to see average rating

### ISSUE THREAD

**Issue by BunmiAdelana** [BunmiAdelana/Marketplace#4]
https://github.com/BunmiAdelana/Marketplace/assets/145928938/595a280d-ebec-4310-9720-5987073acc2f

**Comment by rebekah-oj** [comment]
this is probably because the product does not have any ratings on it, can you confirm that this is the case for all the products available on marketplace? @BunmiAdelana

**Comment by BunmiAdelana** [comment]
@rebekah-oj Yes I confirm that

**Comment by rebekah-oj** [comment]
i'll check
