### ISSUE TITLE
I had to wait for a very long time before my default information comes up & sometimes i have to tap the edit button before it comes up.

### ISSUE THREAD

**Issue by BunmiAdelana** [BunmiAdelana/Marketplace#6]
https://github.com/BunmiAdelana/Marketplace/assets/145928938/40c11195-0b7b-4866-9c2d-fc7f7ef8fbc1

**Comment by rebekah-oj** [comment]
noted

**Comment by rebekah-oj** [comment]
this title is too long, the title should say what the issue is and supporting information can come in the description.


please rewrite. @BunmiAdelana

**Comment by rebekah-oj** [comment]
this title is too long, the title should say what the issue is and supporting information can come in the description.


please rewrite. @BunmiAdelana

**Comment by BunmiAdelana** [comment]
@rebekah-oj duly noted. I'll rewrite it

**Comment by BunmiAdelana** [comment]
@rebekah-oj Done

**Comment by BunmiAdelana** [comment]
@rebekah-oj this has been resolved. It has Passed
